version: 2.1

jobs:
  build-and-test:
    docker:
        - image: medipixel/rl_algorithms
    steps:
      - checkout
      - run:
          command: make dev
          name: Install requirements
      - run:
          command: make test
          name: Test
      - run:
          command: make integration-test
          name: Integration test

workflows:
  main:
    jobs:
      - build-and-test
