version: 2.1

jobs:
  build-and-test:
    docker:
        - image: medipixel/rl_algorithms
    steps:
      - checkout
      - run:
          name: Install requirements
          command: make dev
      - run:
          command: |
            python tests/integration/test_run_agent.py
          no_output_timeout: 60m
      - run:
          name: Test
          command: make test

workflows:
  main:
    jobs:
      - build-and-test
