version: 2.1

jobs:
  build-and-test:
    docker:
        - image: medipixel/rl_algorithms
    steps:
      - checkout
      - run:
          name: Install requirements
          command: make dev
      - run:
          command: |
            python tests/integration/test_run_agent.py
          no_output_timeout: 30m
      - run:
          name: Test
          command: make test
      - run:
          name: Integration test
          command: make integration-test
          no_output_timeout: 30m

workflows:
  main:
    jobs:
      - build-and-test
